### ISSUE TITLE
uuids for holidays

### ISSUE THREAD

**Issue by AarneHuttunen** [nager/Nager.Date#201]
It would be really helpful if each holiday would have a fixed uuid attached. This way copying data from year 2020 to 2021 would be a breeze.

**Comment by samtrion** [comment]
In this context, not only individual countries should be considered, but there should be a central list of UUIDS. So that we can synchronize e.g. the 25.12. in Germany and the Netherlands.

That means here a fundamental Refactoring would have to take place, and would go along with a Breaking Change.
