### ISSUE TITLE
US Independence Day is reported <> July 4

### ISSUE THREAD

**Issue by 1627834** [nager/Nager.Date#214]
US Independence Day is July 4 (fixed). Nager.at reports it on July 3, 2020 and July 5, 2021.

**Comment by tinohager** [comment]
Here is a day shift for the weekend
https://github.com/nager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/UnitedStatesProvider.cs#L51

**Comment by tinohager** [comment]
I have also checked another project and they don't have a fixed setting for this holiday
https://github.com/commenthol/date-holidays/blob/38129116150aa21e97240937e4c11b8b7ff83d4b/data/countries/US.yaml#L76

**Comment by joaomatossilva** [comment]
The US Independence day is in fact on July 4, but since it falls into a weekend, the holiday is observed on the working day before (or after) the weekend.
In [My project](https://github.com/joaomatossilva/DateTimeExtensions) I also do the same "shift", but for sure is a good thing to add a more explicit notion of where it is a holiday vs where the holiday is observed.

**Comment by tinohager** [comment]
@joaomatossilva So you would suggest to include an additional field with the date of origin?

**Comment by joaomatossilva** [comment]
I think a better solution is to create a replica instead of shifting. Because the holiday itself is in fact on the 4th of July, but due to special circumstances (falling on a weekend), it's **also** observed on the 3rd July

for example:
![image](https://user-images.githubusercontent.com/381718/97550513-aefeff00-19c9-11eb-973a-8c4d10571305.png)

**Comment by jbenzing** [comment]
Hello @tinohager, I agree with @joaomatossilva.  I was testing this out to warn our  job schedulers that they are picking a holiday.  If we are busy and working weekends, the holiday may be missed by GetPublicHolidays() when it is shifted for the weekend.    The original entry, and a duplicate with (observed) would be very helpful.

**Comment by tinohager** [comment]
We will definitely include this functionality. But since it will be a major rebuild, I don't know when. But you can help to speed up the whole thing by supporting the project with a sponsorship.

**Comment by Codain** [comment]
See alternative proposal in https://github.com/nager/Nager.Date/issues/419#issuecomment-1563483539 to give time for a proper Specification Class.

**Comment by tinohager** [comment]
In the new version of nager.date we have now the ObservedDate and the Date i think this will fix this issue
