### ISSUE TITLE
Should DateSystem.IsPublicHoliday not only work on public holidays and not bank+local holidays?

### ISSUE THREAD

**Issue by michael-jakobsen-dk** [nager/Nager.Date#263]
If using DateSystem.IsPublicHoliday(14-05-2021, CountryCode.DK) it gives back the value true.

This date is not a public holiday, but "only" a Bank, School, Optional.

Is this the intended behavior? 

If yes, then maybe an optional switch on the function to only return true for actual Public holidays and not bank,school,optional?

**Comment by samtrion** [comment]
Thanks for your error message. We will take a look at the problem.

Which version of Nager.Date are you using?

**Comment by michael-jakobsen-dk** [comment]
Nuget Nager.Date v.1.28.2 via Visual Studio (C#)

**Comment by samtrion** [comment]
Will be released in the next NuGet package.

**Comment by michael-jakobsen-dk** [comment]
Cool. Thank you and excellent/easy package by the way .

**Comment by CasperWSchmidt** [comment]
I was part of extending the DK provider some years ago. Our code relies on IsPublicHoliday and upgrading to 1.29.0 breaks our code (and luckily our unit tests as well). For the future, would you please consider following the semver scheme which would have made 1.29.0 as 2.0.0 instead since this change was breaking existing behaviour that others could rely on :)
