### ISSUE TITLE
New holiday 1 November 2021 in South Africa 

### ISSUE THREAD

**Issue by GeorgeB2009** [nager/Nager.Date#334]
**Which country is affected?** South Africa

**Which public holiday is affected?** 1 November 2021

**Which version of Nager.Date is used?** 1.30.0

**Additional context** https://www.gov.za/about-sa/public-holidays
Elections happening on 1 November and the government recently announced that the day was a public holiday to allow people to vote.

**Comment by GeorgeB2009** [comment]
Too late to change now. It's a once off public holiday for elections.

**Comment by samtrion** [comment]
It's a shame we couldn't help you in time. However, we also try to have a historical view of possible holidays. Therefore, I am reopening this issue.

**Comment by beevabeeva** [comment]
I think this is an unreasonable request. Especially this year, where the date was contested and debated.
The date was only announced on the 22nd of October.
This issue was only made on the 27th of November.

If you really wanted this, a local developer would need to create pull requests as soon as the date is announced.

The 2024 elections do not even have a specific date yet, as far as I can tell:
![image](https://user-images.githubusercontent.com/19332617/143848353-2fac8e71-c879-4e94-93bf-7bb3d84b1e54.png)
