### ISSUE TITLE
US Christmas is off by 1 day (24/12/2021 instead of 25/12/2021)

### ISSUE THREAD

**Issue by duke4e** [nager/Nager.Date#358]
**Which country is affected?**
US

**Which public holiday is affected?**
Christmas

**Which version of Nager.Date is used?**
The one used by your website provided in link below

**Additional context**
https://date.nager.at/PublicHoliday/Country/US

**Comment by tinohager** [comment]
Source file for this holidays
https://github.com/nager/Nager.Date/blob/master/src/Nager.Date/PublicHolidays/UnitedStatesProvider.cs

this holiday is postponed since it falls on a Saturday (https://en.wikipedia.org/wiki/Federal_holidays_in_the_United_States)
> e.g. a holiday falling on a Saturday is observed on the preceding Friday, while a holiday falling on a Sunday is observed on the succeeding Monday

**Comment by Blastnsmash** [comment]
Is there a function that gives us the holiday in a format that is not postponed?

**Comment by hmemcpy** [comment]
Just came here to ask this as well. Turns out that the 24th was not observed by all institutions (banks, mainly) in the US, so even though the rule applies (observed on a preceding Friday) - it might not always be the case.

So asking the same question as @Blastnsmash: is there a way to get the holidays without shifting to the preceding/succeeding days?

**Comment by Codain** [comment]
See proposal in https://github.com/nager/Nager.Date/issues/419#issuecomment-1563483539

**Comment by tinohager** [comment]
In the new version of nager.date we have now the ObservedDate and the Date i think this will fix this issue
