### ISSUE TITLE
Spain - Move "NAVIDAD" from 25-Dec to 26-Dec in Madrid calendar

### ISSUE THREAD

**Issue by florin-bujoreanu** [nager/Nager.Date#399]
### Affected country

Spain

### Affected public holiday

NAVIDAD

### Source of the information

https://www.boe.es/diario_boe/txt.php?id=BOE-A-2021-17113

https://www.comunidad.madrid/en/notas-prensa/2021/09/22/comunidad-madrid-aprueba-calendario-laboral-2022-12-dias-festivos-dos-locales-fijan-municipios

### More information

approved in September 2021

**Comment by fidelpita** [comment]
Navidad (Christmas day) falls on a Sunday so the national public holiday has been moved to the following day (Monday 2022-12-26) for all regions (not just Madrid) **except** for these ones (so no longer a national public holiday):
 - Cataluña (ES-CT): because 26/Dec is already a public holiday (Sant Esteve)
 - Pais Vasco (ES-PV)
 - Comunitat Valenciana (ES-VC)
 - Ceuta (ES-CE)

**Comment by tinohager** [comment]
@fidelpita 
Okay, I understand that and are these changes permanent or do they only apply to 2022 and the next Sunday it will be decided again whether the holiday will be moved?

**Comment by fidelpita** [comment]
@tinohager 
I'm afraid that one cannot assume that the next time that Christmas day falls on a Sunday, it will be the same. The different regions may decide to change their public holidays.
