### ISSUE TITLE
Chile - National Day of Indigenous Peoples

### ISSUE THREAD

**Issue by islaman** [nager/Nager.Date#485]
### Affected country

Chile

### Affected public holiday

National Day of Indigenous Peoples

### Source of the information

https://www.feriados.cl/

### More information

According the chilean law, in the act n°21.357, Chile celebrates the 21th June of each year the winter solstice as national day of Indigenous people (local name: "Día Nacional de los pueblos indígenas")

Source: https://www.conadi.gob.cl/dianacionalpueblosindigenas

**Comment by tinohager** [comment]
The date of the holiday is unfortunately not fixed, it depends on the winter solstice which would have to be calculated astronomically. It takes place when one of the two poles of the earth reaches its maximum inclination to the sun.

The only option at the moment is to create a reference table for the next few years, which would have to be constantly updated.

According to Wikipedia, the holiday is new since June 2021.
