### ISSUE TITLE
Australia - VIC - Friday before AFL Grand Final missing

### ISSUE THREAD

**Issue by mleech** [nager/Nager.Date#565]
### Affected country

Australia - VIC

### Affected public holiday

Friday before AFL Grand Final (Australian Football League)

### Source of the information

https://en.wikipedia.org/wiki/Public_holidays_in_Australia

### More information

See also:
https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2023

From https://en.wikipedia.org/wiki/Public_holidays_in_Australia :
"In August 2015, the day before the [AFL Grand Final](https://en.wikipedia.org/wiki/AFL_Grand_Final), as well as Easter Sunday, were gazetted as Public Holidays within Victoria. This date of the holiday is as gazetted by the Victorian Government and cannot be accurately predicted. In 2019, the Victorian Parliament legislated the AFL Grand Final public holiday by amending the Public Holidays Act 1993 (Vic)."

A note [here](https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2024) says:
"Friday before AFL Grand Final typically falls on the last Friday in September. This website will be updated with the exact date upon release of the 2024 AFL schedule."

**Comment by tinohager** [comment]
Looks very much like an annual handicraft

2018 - 28. Sep (last Friday)
2019 - 27. Sep (last Friday)
2020 - 23. Oct
2021 - 24. Sep (last Friday)
2022 - 23. Sep (not last Friday)
2023 - 29. Sep (last Friday)


- 2021 info
Friday before AFL Grand Final typically falls on the last Friday in September or the first Friday in October when the AFL Grand Final is scheduled each year. The AFL have announced the 2021 Grand Final will take place on 25 September 2021.

- 2020 info
The Friday before Grand Final public holiday is based on the AFL playing schedule, which may be altered due to the response to COVID‑19. We will update the dates on this page if new information becomes available.
