### ISSUE TITLE
United Kingdoms - New Year's Day Duplication

### ISSUE THREAD

**Issue by keeday** [nager/Nager.Date#707]
### More information

Hi,

I'm exploring the API, and I noticed that for the United Kingdoms, New Year's Day appears three times;

![image](https://github.com/user-attachments/assets/9a1d79c1-12d9-433a-9281-e40f26093447)

Am I missing something? Should this not just appear once, and be flagged as National?

**Comment by tinohager** [comment]
The constelation unfortunately results from the fact that the holidays have different sets of rules, they do not have to be on the same day, they can be shifted. You could consider merging the editions if it turns out that they fall on the same day.

https://github.com/nager/Nager.Date/blob/01a65f3826fa96832be49c45a5679814490b17b7/src/Nager.Date/HolidayProviders/UnitedKingdomHolidayProvider.cs#L65-L90

`GB-SCT` should be possible to move to `GB-ENG`, `GB-WLS`

**Comment by keeday** [comment]
Interesting... I actually had no idea that the New Year's Day holiday shifted to Monday if it occurred on a weekend.
Ngl, I thought it was an error until I googled it.

Thank you for educating me! :)

**Comment by tinohager** [comment]
Thanks for reporting and the further information
